미션 유틸 라이브러리를 개선한다
woowacourse-projects/javascript-mission-utils pull request #2
Opened 2023-09-07 01:53 UTC by woowahan-cron

2023-09-07 08:06 UTC, woowapark requested changes
크론 우선 먼저 확인해보면 좋을 부분들만 남겨두었습니다~!    
본문에 말씀해주신 코멘트를 찾지 못해서, 다시 알려주시면 추가로 확인해볼게요! 
고생 많으셨습니다 👏👏👏

2023-09-07 08:06 UTC, woowapark commented on src/console.js
> +      throw new Error("arguments must be 2.");
r: 저희 린트가 필요하겠군요ㅋㅋㅋ(설정이 따로 없었네요....?)

2023-09-07 08:06 UTC, woowapark commented on test/console.test.js
> +describe("Console.print", () => {
r: 린트가 필요하겠네요(2)ㅋㅋㅋ 혹시 이 PR 내에서 포맷팅만 달라서 변경점으로 잡힌 부분은 제거할 수 있을까요?

2023-09-07 08:06 UTC, woowapark commented on src/console.js
> +  }
r: 오옹 Promise API를 따로 제공해주는 것으로 알고 있었는데, 혹시 직접 Promise로 감싸는 것과 차이가 있을까요?-?     
ref) https://nodejs.org/api/readline.html#promises-api
```js 
const readlinePromises = require('node:readline/promises');
const rl = readlinePromises.createInterface({
  input: process.stdin,
  output: process.stdout,
});
```

2023-09-07 08:06 UTC, woowapark commented on src/mocker.js
> +class Mocker {
r: 일반적으로 테스팅 라이브러리들에서도 `Mock`이라고 사용하고, 실제로 용어상 부를 때에도 동일하게 목(Mock)이라고 부르는 것으로 알고 있습니당. 특별히 다른 의도를 드러내기 위함이 아니라면 같은 용어를 사용해도 되지 않을까요? 🙂    
- https://sinonjs.org/releases/v15/mocks/ 
- https://jestjs.io/docs/mock-functions

2023-09-07 08:06 UTC, woowapark commented on src/mocker.js
> +}
r: 이름은 Mocker이지만 내부적으로는 Mock의 역할과 Assertion의 역할을 모두 하고 있는 것 같아요. 아마 기존의 미션 코드 내에서 반복적으로 사용하는 부분을 그대로 옮겨오다보니 둘 다를 포함하게 된 게 아닐까 싶은데요. 🤔
역할과 모듈을 구분해보면 좋을 것 같아요 (꼭 채점 코드 내에 반복되는 부분 모두를 내장할 필요는 없다고 생각해요!      조금 더 편리하게 작성해보자 정도가 달성되면 충분하지 않을까 싶습니당)      
예를 들어, mission-utils 라이브러리같은 경우 Assertion이 따로 먼저 구현되어 있습니당    
https://github.com/woowacourse-projects/mission-utils/blob/main/src/main/java/camp/nextstep/edu/missionutils/test/Assertions.java

2023-09-07 08:33 UTC, woowahan-cron commented on test/console.test.js
> -describe('Console.question', () => {
Console.question이라는 메서드가 없고 대신 readline이라는 메서드가 있습니다.
이를 수정했는데 git diff에서는 아래의 모든 코드가 영향을 받은 것처럼 보이는군요..🥲

2023-09-07 08:33 UTC, woowahan-cron commented on src/console.js
> +  static readLineAsync(query) {
보다 적합한 메서드 이름이 있다면 추천 부탁드립니다

2023-09-07 08:33 UTC, woowahan-cron commented on test/console.test.js
> +describe("Console.readline", () => {
### 테스트 코드 리팩터링 ⚠️아님⚠️ 주의
위의 17번째 줄 "Console.question"을 "Console.readline"로 바꿨을 뿐이에요!
새로 작성한 테스트 케이스도 아니고 수정하지 않았고 리팩터링한 것도 아니니 diff 사항은 그냥 스킵해주세용!

2023-09-07 08:33 UTC, woowahan-cron commented on test/console.test.js
> +describe("Console.readlineAsync", () => {
새로 작성한 테스트 케이스는 이곳부터입니다!

2023-09-07 08:33 UTC, woowahan-cron commented on src/mocker.js
> +  };
이전 미션 테스트코드에서 작성되는 코드를 그대로 가져와서 비동기 작업에 영향을 받는 부분을 일부 수정하였습니다.

2023-09-07 08:33 UTC, woowahan-cron commented on src/mocker.js
> +class Mocker {
class 이름부터 메서드 이름까지 보다 적절한 네이밍이 있다면 추천 부탁드려요!

2023-09-07 08:33 UTC, woowahan-cron commented on src/mocker.js
> +  }
모킹 함수를 유틸 라이브러리로 제공할 때 걸리는 부분이 있는데요! 바로 랜덤 모킹함수 부분입니다.
자동차 경주에서는 `Random.pickNumberInRange`를 사용하지만, 로또 미션에서는 `Random.pickUniqueNumbersInRange`를 사용하고 있고 Random 클래스에는 다양한 static 메서드가 있습니다.

모킹 함수까지 유틸 라이브러리로 제공하는 것과 관련해 생각할 거리가 많아지는데 이것을 제공하는 것이 맞을지 판단이 서질 않네요ㅠ

이 모킹 함수를 자동차 경주 Jest버전에서 테스트를 시도할 때 아래와 같은 이슈가 발생합니다.

## 발생 현황

```
 FAIL  __tests__/ApplicationAllTest.jsLoc=t[2],r.afterLoc=t[3]),this.tryEntries.push(r)}function A(t){var r=t.completion||{};r.type="normal",delete r.arg,t.completion=r}function N(t){this.tryEntries=[{tryLoc:"root"}],t.forEach(I,this),

  ● Test suite failed to run

    Jest worker encountered 4 child process exceptions, exceeding retry limit

      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:21)

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.327 s
Ran all test suites.
```

## 확인 방법

- 저장소: woowacourse-projects/mission-frontend
- 브랜치: feat/racingcar-jest-async-nm

```
--- solution 디렉터리 접근 후
nvm use 18.17.1
git checkout feat/racingcar-jest-async-nm
npm i
--- node_modules/@woowacourse/mission-utils 이하에 유틸 라이브러리를 빌드한 파일 옮겨두기
npm run test
```

2023-09-07 08:35 UTC, woowahan-cron commented on test/console.test.js
> +describe("Console.print", () => {
요것도 리뷰해 주신 내용과 함께 작업할게요!
ESLINT 설정하실 때 페어로 같이 진행하시죠 ㅎㅎ

2023-09-07 23:55 UTC, woowahan-cron commented on src/console.js
> +  }
저도 readline/promises API가 v17버전부터 도입되어서 이걸 사용하면 좋겠다고 생각했는데요!
아직 [Stability: 1](https://nodejs.org/api/documentation.html#stability-index) - Experimental 수준인데 이것을 사용해도 괜찮을까요? 가이드 상으로는 production 환경에서 이 기능을 사용하는 것을 권장하지 않는다고 해서요!

<img width="928" alt="image" src="https://github.com/woowacourse-projects/javascript-mission-utils/assets/112997662/efd8cb60-0559-4536-bf31-4bf0b1f9ea26">

<img width="929" alt="image" src="https://github.com/woowacourse-projects/javascript-mission-utils/assets/112997662/28b62ae8-4c98-4b3a-a859-72dd718756e9">

2023-09-07 23:59 UTC, woowahan-cron commented on src/mocker.js
> +class Mocker {
넵! 저도 이름 지을 때 고민했던 부분이었는데요! 일반적인 사용이 Mock이라고 한다면 이름을 고쳐보는 것이 좋을 것 같아요.
다만, 제가 모킹 함수와 관련된 이슈 코멘트가 Pending인 상태를 모르고 있다가 그 사이 공원이 리뷰를 해주셔서 [이슈](https://github.com/woowacourse-projects/javascript-mission-utils/pull/2#discussion_r1318013123)와 관련된 코멘트를 확인 요청을 먼저 드려야 할 것 같습니다 😭😭😭 

**이슈에 관한 문제가 없는 것을 확인하면 그때 현재 Mocker 클래스와 관련된 코드 리뷰를 일괄 적용해도 괜찮을까요?**

2023-09-08 00:00 UTC, woowahan-cron commented on src/console.js
> +      throw new Error("arguments must be 2.");
그러면, 린트는 다음번 이슈에서 적용하기로 하고 이번에는 포매팅이 다른 부분 제거해서 다시 커밋할게요!

2023-09-12 01:29 UTC, woowahan-cron commented on .prettierrc
이 이슈에서 ESLINT를 설정하기에는 무리일 것 같아서 급한 대로 prettierrc 설정을 이용해서 따옴표와 들여쓰기 너비만 수정해 봤는데 괜찮을까요? (왠지 안 괜찮을 것 같은데 일단 올려봅니다...ㅎㅎ 개선이 필요한 점 말씀해 주세요🥲)

2023-09-12 05:32 UTC, woowapark commented on package.json
>      "url": "git+https://github.com/woowacourse-projects/javascript-mission-utils.git"
버전 업데이트도 같이 필요할 것 같아요! 🙂

2023-09-12 05:32 UTC, woowapark commented on test/console.test.js
> -describe('Console.question', () => {
아마 탭 사이즈가 바뀌어서 변경 사항으로 잡히는 것 같아요! 
요것도 혹시 diff에 안잡히게 돌려주실 수 있을까용? :) 
린트 적용하면서 한번에 싹 바꾸면 좋을 것 같아요!

2023-09-12 05:32 UTC, woowapark commented on src/mocker.js
> +  }
크론~ 알려주신 브랜치에서의 오류들 우선 확인해보았습니다!       
- (1) 일단 26번째 라인에서 `getLogSpy()를 찾아오지 못해 생기는 문제인 것 같아요. 라이브러리 자체에서 문제가 있어서 그걸 사용하는 쪽에서 오류가 나는 경우로 보입니당 
   ```js 
   // AS-IS
   const logSpy = getLogSpy(); 
   
   // TO-BE 
   const logSpy = Mocker.getLogSpy(); 로 해야 오류가 나지 않을 것 같습니다. 
   ```
   - 요런 부분들이 (필요하다면) 라이브러리쪽 테스트 코드에서 검증이 되면 좋을 것 같아요!
- (2) getLogSpy() 관련 이슈를 해결해도 아래와 같은 에러가 다시 발생하는데요. 
   ```
   ReferenceError: regeneratorRuntime is not defined
   ```
   async/await 설정이 들어간 상태라, async/await 문법도 잘 트랜스파일 되도록 바벨 설정도 추가해서 빌드를 해야 할 것 같습니다.
- (3) 그 이후에는 요 에러가 이어서 발생합니다. 
   ```
   TypeError: callback is not a function
   ```    
   요건 solution 내에서 `Mocker.run()` 을 실행하실 때 'callback' 인자를 깜빡하신 것 같아요! 요것까지 넣어주면 테스트 자체 실행은 되는 것 같습니당~ 
- 위 이슈들과 별개로 모킹 함수는 지원자들이 사용할 수 있게 제공하는 용도라기보다 저희가 채점 코드를 작성할 때에 편의를 높여주는 용도로 보아도 될 것 같은데 어떠신가요?

2023-09-12 06:51 UTC, woowahan-cron commented on src/mocker.js
> +  }
ㅠㅠ 제가 몇 군데 빼먹은 부분이 있어서 그런 거였군요;;

아하~! 지원자들이 사용할 수 있는 용도가 아니라면 미션 유틸 라이브러리에 제공할 필요는 없을 것 같다고 생각해요! 다만, 저희의 편의를 위해서 추가했을 때 그만한 가치가 있을지는 제가 판단이 잘 서질 않는데요🥲 프리코스를 여러 번 진행해 보신 공원과 준의 의견을 더 들어보고 싶습니다. 이 부분은 내일 같이 논의해 보실까요?!

2023-09-13 05:20 UTC, woowahan-cron commented on src/mocker.js
> +}
1. 지원자들에게 모킹함수 유틸 사용이 필요한가 -> 프론트 코치 전원 X
2. 채점을 위해 편의성을 고려하기 위해 유틸 함수를 내장시킬 것인가 -> 고려

2023-09-13 05:21 UTC, woowahan-cron commented
## 커리큘럼 회의 논의

1. 모킹 함수 내장 여부
2. Promise 구현 함수 추가 필요한 부분
   - 프리코스 문제 검토해 보기
   - README.md

2023-09-13 10:13 UTC, woowapark commented on src/mocker.js
> +  }
크론 혹시 새로 업데이트해주신 기준으로 라이브러리를 미션에서 사용할 때 요 에러는 발생하지 않나요...?-?        
```
ReferenceError: regeneratorRuntime is not defined
```
async/await 구문을 사용하지 않다가 추가한 부분이라 트랜스파일 설정도 추가해서 빌드해야 하지 않나 해서요!

2023-09-15 04:46 UTC, woowahan-cron commented on src/console.js
> +  }
혹시 모르니 Promise 객체를 래핑하는 것으로 땅땅

2023-09-19 02:29 UTC, woowahan-cron commented on src/mocker.js
> +  }
앗.. 마지막 말씀해 주신 부분 제가 정신이 없는 바람에 지나쳤나 봐요ㅠ
이 부분은 모킹과 관련된 내용을 제거했을 때는 해당되지 않는 이슈이겠죠?

2023-10-10 02:30 UTC, woowahan-cron commented
[새로운 PR](https://github.com/woowacourse-projects/javascript-mission-utils/pull/5)에서 같은 이슈 작업을 진행하였으므로 해당 PR은 닫습니다.

2023-10-10 02:30 UTC, closed without merging